register:
  path: /register
  controller: App\Controller\Api\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check
  controller: App\Controller\Api\AuthController::getTokenUser
  methods: POST

test:
  path: /api/test
  controller: App\Controller\Api\ApiController::test
